#!/bin/bash

SELF=$(readlink -f "$0")
HERE=${SELF%/*}

BWRAP_OPTIONS="--bind $HERE/root /                   \
    --share-net                                      \
    --bind /home /home                           \
    --bind /tmp /tmp			     \
    --dev-bind /dev /dev                             \
    --proc /proc			             \
    --bind-try /run /run                             \
    --bind-try /sys /sys                             \
    --bind-try /mnt /mnt                             \
    --bind-try /home /home                           \
    --ro-bind-try /etc/machine-id /etc/machine-id    \
    --ro-bind-try /etc/resolv.conf /etc/resolv.conf  \
    --ro-bind-try /etc/passwd /etc/passwd            \
    --ro-bind-try /etc/hosts /etc/hosts              \
    --ro-bind-try /etc/nsswitch.conf /etc/nsswitch.conf \
    --ro-bind-try /etc/group /etc/group              \
    --setenv SELF \"$SELF\"                          \
    --setenv SELF_TEMPDIR \"$HERE/root\"             \
    --setenv GTK_ICON_THEME Adwaita                  \
    --setenv BWROOTFS \"$HERE/root\"                 \
    --setenv ARGV0 \"$ARGV0\"                        \
    --setenv ARGS \"$@\"                             \
    --setenv WITHIN_BWRAP \"1\"                      \
    --cap-add CAP_NET_BIND_SERVICE                   \
    --cap-add CAP_SYS_ADMIN"

# Executa virt-manager dentro do bwrap
$HERE/bwrap $BWRAP_OPTIONS kodi "$@" | cat
